apiVersion: v1
kind: Service
metadata:
  name: playa3ulldemoapp-svc
spec:
  selector:
    app: playa3ulldemoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
