apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: playa3ulldemoapp-servicemonitor
    release: prometheus
  name: playa3ulldemoapp-servicemonitor
  namespace: monitoring
spec:
  jobLabel: job
  endpoints:
    - interval: 2s
      port: playa3ulldemoapp-port
      path: /metrics
  selector:
    matchLabels:
      app: playa3ulldemoapp
  namespaceSelector:
    matchNames:
      - default
