name: Node.js App Deploy to Docker Hub and EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read Version from File
        id: version
        run: |
            VERSION=$(cat ./node-app/LATEST_VERSION)
            echo "VERSION=$VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV    

      # Step 5: Build, Tag, and Push Docker Image
      - name: Build, Tag, and Push Docker Image to Docker Hub
        env:
          IMAGE_TAG: ${{ env.VERSION }}
        run: |
          docker build -t naveen75/playa3ulldemo:$IMAGE_TAG ./node-app
          docker push naveen75/playa3ulldemo:$IMAGE_TAG
        continue-on-error: false  

      # Step 6: Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-cluster

      # Step 7: Deploy to EKS with Error Handling
      - name: Deploy to EKS
        id: deploy
        run: |
          echo "Starting deployment to EKS..."
          kubectl apply -f ./eks/playa3ull-app-deployment.yaml
          echo "Waiting for deployment to stabilize..."
          kubectl rollout status deployment/playa3ulldemoapp --timeout=120s

      # Step 8: Rollback on Failure
      - name: Rollback Deployment on Failure
        if: ${{ failure() }}
        run: |
          echo "Deployment failed. Initiating rollback..."
          kubectl rollout undo deployment/playa3ulldemoapp